### ISSUE TITLE
Cannot use 'in' operator to search for 'data' in null

### ISSUE THREAD

**Issue by n1n3b1t** [petecoop/generator-express#116]
Hi guys I've just installed this generator it works awesome with any template engine except handlebars.
```
TypeError: Cannot use 'in' operator to search for 'data' in null
   at Object.compile (/home/n1n3b1t/nodeProjects/RHAPI/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:467:19)
   at HandlebarsEnvironment.hb.compile (/home/n1n3b1t/nodeProjects/RHAPI/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars.js:34:41)
   at ExpressHandlebars._compileTemplate (/home/n1n3b1t/nodeProjects/RHAPI/node_modules/express-handlebars/lib/express-handlebars.js:239:28)
   at ExpressHandlebars.<anonymous> (/home/n1n3b1t/nodeProjects/RHAPI/node_modules/express-handlebars/lib/express-handlebars.js:124:25)
   at /home/n1n3b1t/nodeProjects/RHAPI/node_modules/express-handlebars/node_modules/promise/lib/core.js:33:15
   at flush (/home/n1n3b1t/nodeProjects/RHAPI/node_modules/express-handlebars/node_modules/promise/node_modules/asap/asap.js:27:13)
   at process._tickCallback (node.js:419:13)
```
```
n1n3b1t@r2d2:~/nodeProjects/RHAPI$ npm version                                                                                                                 │
{ http_parser: '1.0',                                                                                                                                          │
  node: '0.10.28',                                                                                                                                             │
  v8: '3.14.5.9',                                                                                                                                              │
  ares: '1.9.0-DEV',                                                                                                                                           │
  uv: '0.10.27',                                                                                                                                               │
  zlib: '1.2.3',                                                                                                                                               │
  modules: '11',                                                                                                                                               │
  openssl: '1.0.1g',                                                                                                                                           │
  npm: '1.4.10',                                                                                                                                               │
  rhapi: '0.0.1' }
```
I've tried to google the issue but didn't find anything about it.

**Comment by n1n3b1t** [comment]
I've checked express-handlebars and handlebars.js for now they suggest temporary workaround passing compilerOption: undefined. So you can add it to handlebars app.js code in generator

**Comment by petecoop** [comment]
see https://github.com/wycats/handlebars.js/issues/1003
