### ISSUE TITLE
Installed version of gulp-less produces errors

### ISSUE THREAD

**Issue by mikeerickson** [petecoop/generator-express#157]
Using the default package.json (should consider testing against latest versions) the following error is produced.   When I update to latest gulp-less (3.x.x) all works fine.

````
$ npm uninstall -D gulp-less && npm install -D gulp-less
````

````
/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/mikee/Documents/Projects/dev/node/players/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
````

**Comment by petecoop** [comment]
`"gulp-less": "^3.0.1"` https://github.com/petecoop/generator-express/blob/master/app/templates/mvc-shared/package.json#L48
