### ISSUE TITLE
How to include socket.io 

### ISSUE THREAD

**Issue by rajkaran** [petecoop/generator-express#178]
I am trying to include socket.io to my app but, couldn't figure out how to achieve this. I can only find solutions for the file system generated with older version of this generator (based on bin/www).

Below is my code.
**Configuration**
app.js

```
var express = require('express');
var config = require('./config/config');

var app = express();
var expressWs = require('express-ws')(app);
var server = require('http').Server(app);
var io = require('socket.io')(server);

require('./config/express')(app, config, server);

app.listen(config.port, function () {
  console.log('Express server listening on port ' + config.port);
});
```

express.js

```
var express = require('express');
var glob = require('glob');

var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var compress = require('compression');
var methodOverride = require('method-override');
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type');
    next();
}

module.exports = function(app, config, server) {
  var env = process.env.NODE_ENV || 'development';
  app.locals.ENV = env;
  app.locals.ENV_DEVELOPMENT = env == 'development';
  
  app.set('views', config.root + '/app/views');
  app.set('view engine', 'jade');

  // app.use(favicon(config.root + '/public/img/favicon.ico'));
  app.use(logger('dev'));
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({
    extended: true
  }));
  app.use(cookieParser());
  app.use(compress());
  app.use(express.static(config.root + '/public'));
  app.use(methodOverride());
  app.use(allowCrossDomain);

  var controllers = glob.sync(config.root + '/app/controllers/*.js');
  controllers.forEach(function (controller) {
    require(controller)(app, server);
  });

  app.use(function (req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
  });
  
  if(app.get('env') === 'development'){
    app.use(function (err, req, res, next) {
      res.status(err.status || 500);
      res.render('error', {
        message: err.message,
        error: err,
        title: 'error'
      });
    });
  }

  app.use(function (err, req, res, next) {
    res.status(err.status || 500);
      res.render('error', {
        message: err.message,
        error: {},
        title: 'error'
      });
  });

app.use(function(req, res, next){
	res.io = io;
	next();
  });

};
```

config.js

```
var path = require('path'),
    rootPath = path.normalize(__dirname + '/..'),
    env = process.env.NODE_ENV || 'development';

var config = {
  development: {
    root: rootPath,
    app: {
      name: 'nodejswebsocketapp'
    },
    port: process.env.PORT || 3000,
  },

  test: {
    root: rootPath,
    app: {
      name: 'nodejswebsocketapp'
    },
    port: process.env.PORT || 3000,
  },

  production: {
    root: rootPath,
    app: {
      name: 'nodejswebsocketapp'
    },
    port: process.env.PORT || 3000,
  }
};

module.exports = config[env];
```

**Server side**
socketIOController.js

```
var express = require('express'),
	router = express.Router();

module.exports = function (app) {
  app.use('/', router);
  app.use('/socket', router);
  //app.use('/socketio', router);
};

router.get('/socket', function (req, res, next) {
	res.io.emit("socketToMe", "users");
    res.render('socketio', {
      title: 'This is Socket IO Simulator',
    });
});
```

**Client side**
socketio.jade
```
doctype html
html(lang='en')
  head
    meta(charset='UTF-8')
    meta(name='viewport', content='width=device-width')
    title= title
    block css
      link(rel='stylesheet', href='/css/style.css')
    block js
      if ENV_DEVELOPMENT
        script(src='http://whflipdev01.wh.tvh.ca:35729/livereload.js')
      script(src='http://whflipdev01.wh.tvh.ca:3000/components/jquery/dist/jquery.js')
      script(src="http://whflipdev01.wh.tvh.ca:3000/components/socket.io.js")
      script.
       var socket = io('http://whflipdev01.wh.tvh.ca:3000/socketToMe');
       socket.on('socketToMe', function (data) {
         console.log(data);
       });
      
  body
    block content
      h1= title
```

After all of this client can't make connection with server. getting this error:

```
Not Found

404

Error: Not Found
    at C:\xampp\htdocs\xtras\nodejsWebSocketApp\config\express.js:43:15
    at Layer.handle [as handle_request] (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:312:13)
    at C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:330:12)
    at next (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:271:10)
    at C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:618:15
    at next (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:256:14)
    at Function.handle (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:176:3)
    at router (C:\xampp\htdocs\xtras\nodejsWebSocketApp\node_modules\express\lib\router\index.js:46:12)
```

**Comment by petecoop** [comment]
Hey have you tried following the socket.io docs on using with express? http://socket.io/docs/

I can't say I've done much different when adding socket.io to this
