### ISSUE TITLE
unable to connect to database at mongodb

### ISSUE THREAD

**Issue by chenshuxian** [petecoop/generator-express#187]
How can I fix this bug:
Express server listening on port 3000
/Users/jacky/coreCenter/express/node_modules/mongodb/lib/server.js:231
        process.nextTick(function() { throw err; })
                                      ^

Error: unable to connect to database at mongodb://localhost/express-development
    at NativeConnection.<anonymous> (/Users/jacky/coreCenter/express/app.js:10:9)
    at emitOne (events.js:77:13)
    at NativeConnection.emit (events.js:169:7)

    at /Users/jacky/coreCenter/express/node_modules/mongoose/lib/connection.js:288:17
    at NativeConnection.Connection.error (/Users/jacky/coreCenter/express/node_modules/mongoose/lib/connection.js:449:12)
    at /Users/jacky/coreCenter/express/node_modules/mongoose/lib/connection.js:480:15
    at /Users/jacky/coreCenter/express/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:69:21
    at /Users/jacky/coreCenter/express/node_modules/mongodb/lib/db.js:242:14
    at null.<anonymous> (/Users/jacky/coreCenter/express/node_modules/mongodb/lib/server.js:229:9)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/Users/jacky/coreCenter/express/node_modules/mongodb-core/lib/topologies/server.js:218:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
[15:11:24] [nodemon] app crashed - waiting for file changes before starting...

**Comment by petecoop** [comment]
It looks like your database wasn't running? Did you figure this out?
