### ISSUE TITLE
TypeError: Cannot read property 'ENV_DEVELOPMENT' of undefined

### ISSUE THREAD

**Issue by krekoun** [petecoop/generator-express#218]
Hey,

there is a bug in `layout.marko` file. You are trying to access property **ENV_DEVELOPMENT** via `out.global.locals.ENV_DEVELOPMENT` but whenever I open my page in the browser I get this error:

```
TypeError: Cannot read property 'ENV_DEVELOPMENT' of undefined
    at render (/Applications/MAMP/htdocs/davidkregl/personal-website/app/views/layout.marko.js:14:26)
    at Template.render (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/marko/runtime/marko-runtim
e.js:192:9)
    at render (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/marko/taglibs/layout/use-tag.js:23:
22)
    at render (/Applications/MAMP/htdocs/davidkregl/personal-website/app/views/error.marko.js:13:5)
    at Template.render (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/marko/runtime/marko-runtim
e.js:192:9)

    at /Applications/MAMP/htdocs/davidkregl/personal-website/config/express.js:53:21
    at Layer.handle_error (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/laye
r.js:71:5)
    at trim_prefix (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/index.js:31
5:13)
    at /Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router
/index.js:335:12)
    at next (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/laye
r.js:73:5)
    at trim_prefix (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/index.js:31
5:13)
    at /Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router
/index.js:335:12)
    at next (/Applications/MAMP/htdocs/davidkregl/personal-website/node_modules/express/lib/router/index.js:275:10)
```

Changing the code in template to `out.global.ENV_DEVELOPMENT` fixed the error for me.

Should I create PR? 

Thank you for this amazing generator! 👍

**Comment by petecoop** [comment]
`ENV_DEVELOPMENT` is set based on the `NODE_ENV`, by default `NODE_ENV` is set to `development` which will set `ENV_DEVELOPMENT` to `true`. So you either shouldn't need to do anything, or you may need to run with `NODE_ENV=development`

**Comment by selfagency** [comment]
I have my `NODE_ENV` set to development which I am pulling from my `.env` file using [dotenv](https://github.com/motdotla/dotenv), which I have verified is working, and I am nonetheless getting the same error:

```
TypeError: Cannot read property 'ENV_DEVELOPMENT' of undefined
    at render (/Users/daniel/Dev/nylon-graphql/views/layout.marko.js:14:26)
    at Template.render (/Users/daniel/Dev/nylon-graphql/node_modules/marko/runtime/marko-runtime.js:192:9)
    at render (/Users/daniel/Dev/nylon-graphql/node_modules/marko/taglibs/layout/use-tag.js:23:22)
    at render (/Users/daniel/Dev/nylon-graphql/views/error.marko.js:13:5)
    at Template.render (/Users/daniel/Dev/nylon-graphql/node_modules/marko/runtime/marko-runtime.js:192:9)
    at /Users/daniel/Dev/nylon-graphql/app.js:61:19
    at Layer.handle_error (/Users/daniel/Dev/nylon-graphql/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/daniel/Dev/nylon-graphql/node_modules/express/lib/router/index.js:315:13)
    at /Users/daniel/Dev/nylon-graphql/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/daniel/Dev/nylon-graphql/node_modules/express/lib/router/index.js:335:12)
```

**Comment by selfagency** [comment]
oh wait i see, i need to add some variation of

```
  indexTemplate.render({
    $global: {locals: req.app.locals},
    title: 'Express'
  }, res);
```

to my templates

**Comment by selfagency** [comment]
never mind, that did not work either

**Comment by selfagency** [comment]
interestingly any pages other than '/' 404 no matter what the view engine is.

**Comment by petecoop** [comment]
it's the `$global: {locals: req.app.locals},` section, this needs to be included in the renders in `config/express.js`
