### ISSUE TITLE
After generate, got an error

### ISSUE THREAD

**Issue by rafagomes** [petecoop/generator-express#79]
After generate with options: --coffee, mongodb, jade and MVC. Got this error:
```
/Sites/pessoal/app1/node_modules/mongoose/lib/index.js:323
      throw new mongoose.Error.MissingSchemaError(name);
            ^
MissingSchemaError: Schema hasn't been registered for model "Article".
Use mongoose.model(name, schema)
  at Mongoose.model (/Sites/pessoal/app1/node_modules/mongoose/lib/index.js:323:13)
  at Object.<anonymous> (/Sites/pessoal/app1/app/controllers/home.coffee:4:21)
  at Object.<anonymous> (/Sites/pessoal/app1/app/controllers/home.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Sites/pessoal/app1/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Sites/pessoal/app1/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /Sites/pessoal/app1/config/express.coffee:28:5
  at Array.forEach (native)
  at module.exports (/Sites/pessoal/app1/config/express.coffee:27:15)
  at Object.<anonymous> (/Sites/pessoal/app1/app.js:20:28)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```
I ran with gulp and grunt after installation.

$yo express
$gulp

Thanks guys!

**Comment by petecoop** [comment]
This is an issue that has crept in on a new update. It's now fixed and published as 2.5.5
