### ISSUE TITLE
Controller throwing error over mongoose (MVC, Mongo, Handlebars)

### ISSUE THREAD

**Issue by alexkahn** [petecoop/generator-express#85]
# Issue
Just to get it out of the way, here's the traceback.
```
[grunt-develop] > ~/Projects/jats/app/controllers/ticket.js:3

[grunt-develop] >   , Ticket = mongoose.model('Ticket')
             ^

[grunt-develop] > ReferenceError: mongoose is not defined
    at Object.<anonymous> (~/Projects/jats/app/controllers/ticket.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at ~/Projects/jats/config/express.js:75:5
    at Array.forEach (native)
    at module.exports (~/Projects/jats/config/express.js:74:15)
>> application exited with code 8
>> Delayed live reload successful.
```

I have a controller, much like the example `home.js` controller:
```
var express = require('express')
  , router = express.Router()
  , Ticket = mongoose.model('Ticket')
  ;

module.exports = function (app) {
  app.use('/', router);
};

router.get('/tickets', function(req, res, next) {
  // get a list of tickets for a user
  Ticket.find(function(err, tickets) {
    var t = tickets;
    res.render('index', {title: 'Tickets', tickets: t});
  });
});
```

Question is, why wouldn't this controller be able to recognize `mongoose` since nothing in the `/config` directory has changed much (beside some additions) same goes for `app.js`? Can't seem to find anything.

**Comment by petecoop** [comment]
you just look to be missing:

```
mongoose = require('mongoose')
``
before using `mongoose.model`.

I've just tested generating a new project with that setup, the example `home.js` controller looks like this:

```
var express = require('express'),
  router = express.Router(),
  mongoose = require('mongoose'),
  Article = mongoose.model('Article');
```

**Comment by alexkahn** [comment]
Thanks @petecoop!
